# Generated by Django 4.2.6 on 2023-10-30 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('ISIN', models.CharField(max_length=12)),
                ('Trade_date', models.DateField()),
                ('Settlement_date', models.DateField()),
                ('Primary_brocker', models.CharField(max_length=100)),
                ('Sens', models.CharField(max_length=100)),
                ('Trader', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Size', models.IntegerField()),
                ('Price_Type', models.CharField(max_length=10)),
                ('Currency', models.CharField(max_length=10)),
                ('Clean_Dirty', models.CharField(max_length=100)),
                ('Published', models.DateTimeField(default=django.utils.timezone.now)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
