# Generated by Django 4.2.6 on 2023-11-05 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Clean_Dirty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ISIN',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Price_Type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Primary_brocker',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Published',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Sens',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Settlement_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Trade_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Trader',
        ),
        migrations.RemoveField(
            model_name='order',
            name='User',
        ),
        migrations.AddField(
            model_name='order',
            name='clean_dirty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='isin',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='primary_brocker',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sens',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trader',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
