# Generated by Django 4.2.6 on 2023-11-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_brockertrade_subtrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtrade',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='brockertrade',
            name='text_brockertrade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtrade',
            name='text_subtrade',
            field=models.TextField(blank=True, null=True),
        ),
    ]
