# Generated by Django 4.2.6 on 2023-11-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_remove_subtrade_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtrade',
            name='text_subtrade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
