# Generated by Django 4.2.6 on 2023-11-27 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0005_alter_subtrade_text_subtrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='brockertrade',
        ),
        migrations.DeleteModel(
            name='subtrade',
        ),
        migrations.RemoveField(
            model_name='order',
            name='published',
        ),
        migrations.AddField(
            model_name='order',
            name='Timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
