# Generated by Django 4.2.6 on 2023-11-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0006_delete_brockertrade_delete_subtrade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Timestamp',
            new_name='TimeStamp',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
