# Generated by Django 4.2.6 on 2024-03-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0007_rename_timestamp_order_timestamp_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='clean_dirty',
        ),
    ]
