# Generated by Django 4.2.6 on 2024-03-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0008_remove_order_clean_dirty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dealer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
